install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.90.0/hugo_0.90.0_Linux-64bit.deb
  - sudo dpkg -i hugo_0.90.0_Linux-64bit.deb

script:
  - hugo
  
deploy:
  verbose: true
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local-dir: ./public/
  target_branch: master
  on:
    branch: gitbook
