language: node_js
node_js:
  - "10"
cache: npm
branches:
  only:
    - gitbook
notifications:
  email:
    recipients:
      - hnbcao@gmail.com # 设置通知邮件
    on_success: change
    on_failure: always
    
install:
  - npm install -g gitbook-cli
  - gitbook install
  
script:
  - gitbook build
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: master
  on:
    branch: source
  local-dir: _book
