kind: Ingress
apiVersion: extensions/v1beta1
metadata: 
    name: mysql-ingress
    namespace: mysql
    annotations:
        kubernetes.io/ingress.class: traefik
spec:
    rules:
    - host: mysql.seos.segma.tech
      http:
        paths:
        - backend:
            serviceName: mysql-mysql
            servicePort: 3306
          path: /
