kind: Deployment
apiVersion: apps/v1
metadata:
  name: segma-log-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: segma-log-demo
      app.kubernetes.io/name: segma
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: segma-log-demo
        app.kubernetes.io/name: segma
    spec:
      volumes:
        - name: logfilepath
          emptyDir: {}
      containers:
        - name: segma-fluentd
          image: harbor.segma.tech/fluentd/fluent-bit-file:1.3.2
          env:
            - name: FLUENTD_ARGS
              value: '--no-supervisor -q'
            - name: OUTPUT_HOST
              value: 172.16.0.5
            - name: OUTPUT_PORT
              value: '31113'
            - name: LOGSTASH_PREFIX
              value: logstash
            - name: OUTPUT_SCHEME
              value: http
            - name: OUTPUT_SSL_VERSION
              value: TLSv1_2
            - name: OUTPUT_BUFFER_CHUNK_LIMIT
              value: 20M
            - name: K8S_LOG_DIR
              value: /mnt/logs/web
            - name: K8S_HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: K8S_CONTAINER_NAME
              value: segma
            - name: K8S_APPLICATION_NAME
              value: segma-log-demo
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: K8S_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: logfilepath
              mountPath: /mnt/logs/web
          imagePullPolicy: IfNotPresent
        - name: segma
          image: 'harbor.segma.tech/hnbcao/log-demo:v0.0.1'
          ports:
            - name: http
              containerPort: 9009
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: logfilepath
              mountPath: /mnt/logs/web
          imagePullPolicy: IfNotPresent
---
---
kind: Service
apiVersion: v1
metadata:
  name: segma-log-demo
  namespace: default
spec:
  ports:
    - name: web
      protocol: TCP
      port: 9009
      targetPort: 9009
  selector:
    app.kubernetes.io/instance: segma-log-demo
    app.kubernetes.io/name: segma
---
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: segma-log-demo
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: segma-log-demo.segma.tech
      http:
        paths:
          - path: /
            backend:
              serviceName: segma-log-demo
              servicePort: 9009

