expose:
  type: ingress
  ingress:
    hosts:
      core: harbor.segma.tech
      notary: notary.harbor.segma.tech
    # set to the type of ingress controller if it has specific requirements.
    # leave as `default` for most ingress controllers.
    # set to `gce` if using the GCE ingress controller
    # set to `ncp` if using the NCP (NSX-T Container Plugin) ingress controller
    controller: default
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
  
externalURL: https://harbor.segma.tech

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      accessMode: ReadWriteOnce
      size: 500Gi
    chartmuseum:
      accessMode: ReadWriteOnce
      size: 20Gi
    jobservice:
      accessMode: ReadWriteOnce
      size: 1Gi
    database:
      accessMode: ReadWriteOnce
      size: 1Gi
    redis:
      accessMode: ReadWriteOnce
      size: 5Gi

imagePullPolicy: IfNotPresent

logLevel: debug

harborAdminPassword: "302@Segma.Tech"

nginx:
  nodeSelector: 
    beta.kubernetes.io/harbor-cluster: 'true'
  image:
    repository: goharbor/nginx-photon
    tag: v1.8.5

portal:
  nodeSelector: 
    beta.kubernetes.io/harbor-cluster: 'true'
  image:
    repository: goharbor/harbor-portal
    tag: v1.8.5

core:
  nodeSelector: 
    beta.kubernetes.io/harbor-cluster: 'true'
  image:
    repository: goharbor/harbor-core
    tag: v1.8.5

jobservice:
  nodeSelector: 
    beta.kubernetes.io/harbor-cluster: 'true'
  image:
    repository: goharbor/harbor-jobservice
    tag: v1.8.5

registry:
  nodeSelector: 
    beta.kubernetes.io/harbor-cluster: 'true'
  registry:
    image:
      repository: goharbor/registry-photon
      tag: v2.7.1-patch-2819-v1.8.5

  controller:
    image:
      repository: goharbor/harbor-registryctl
      tag: v1.8.5

chartmuseum:
  nodeSelector: 
    beta.kubernetes.io/harbor-cluster: 'true'
  enabled: true
  image:
    repository: goharbor/chartmuseum-photon
    tag: v0.9.0-v1.8.5

clair:
  nodeSelector: 
    beta.kubernetes.io/harbor-cluster: 'true'
  enabled: true
  image:
    repository: goharbor/clair-photon
    tag: v2.0.8-v1.8.5

notary:
  nodeSelector: 
    beta.kubernetes.io/harbor-cluster: 'true'
  enabled: true
  server:
    image:
      repository: goharbor/notary-server-photon
      tag: v0.6.1-v1.8.5

  signer:
    image:
      repository: goharbor/notary-signer-photon
      tag: v0.6.1-v1.8.5

database:
  type: external
  external:
    host: "harbor-postgresql"
    port: "5432"
    username: "postgresql"
    password: "segma@cisdi"
    coreDatabase: "registry"
    clairDatabase: "clair"
    notaryServerDatabase: "notary_server"
    notarySignerDatabase: "notary_signer"
    sslmode: "disable"

redis:
  type: internal
  internal:
    nodeSelector: 
      beta.kubernetes.io/harbor-cluster: 'true'
    image:
      repository: goharbor/redis-photon
      tag: v1.8.5
