kind: Service
apiVersion: v1
metadata:
  name: dind-service
  namespace: segma-store
spec:
  ports:
    - protocol: TCP
      port: 2376
      name: web
  selector:
    name: dind
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dind-ingress
  namespace: segma-store
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: dind.segma-store.seos.segma.tech
    http:
      paths:
        - backend:
            serviceName: dind-service
            servicePort: 2376
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: dind
  namespace: segma-store
  labels:
    name: dind
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dind
  template:
    metadata:
      labels:
        name: dind
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
        - name: varlibdocker
          emptyDir: {}
        - name: dindconfig
          secret:
            secretName: docker-cfg
        - name: rundind
          hostPath:
            path: /var/run/docker.sock
      containers:
      - image: docker:dind
        args:
          - dockerd
          - -H tcp://0.0.0.0:2376
          - --insecure-registry=harbor.seos.segma.tech
        name: segma-app
        securityContext:
          privileged: true
        ports:
        - containerPort: 2376
          name: dind
        volumeMounts:
          - name: varlibdocker
            mountPath: /var/lib/docker
          - name: dindconfig
            mountPath: /root/.docker/config.json
            readOnly: true
          - name: rundind
            mountPath: /var/run/docker.sock
